server:
  port: 8084

spring:
  application:
    name: ADMIN-SERVICE
  h2:
    console:
      enabled: true

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/